image: openjdk:17-jdk

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  paths:
    - .gradle/wrapper
#    - .gradle/caches

stages:
  - test

test:
  stage: test
  variables:
    env: "CI"
  script:
    - ./gradlew -v
    - ./gradlew test --stacktrace
