image: openjdk:17-jdk

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  paths:
    - .gradle/wrapper
#    - .gradle/caches

stages:
  - test
  - build

build:
  image: openjdk:18-jdk-slim
  stage: build
  only:
    - tags
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/Mediator-*.jar
    expire_in: 1 week

test:
  stage: test
  variables:
    env: "CI"
  script:
    - ./gradlew -v
    - ./gradlew test --stacktrace
