image: gradle:7.2.0-jdk16

stages:
  - test

test:
  stage: test
  before_script:
    - rm -rf ./src/main/resources/application.properties
    - cp ./src/main/resources/application.properties.ci-test ./src/main/resources/application.properties
  script:
    - ./gradlew -v
    - ./gradlew test
