name: Conveyor Deploy
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test
        run: ./gradlew test --stacktrace
        env:
          env: CI
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Build
        run: ./gradlew jar -PversionString="${{ github.ref_name }}" # TODO use "proguardReleaseJars" as this also uses Pro-Guard (but there needs to be more configuration [ProGuard, gradle and conveyor])
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Extract secrets
        run: |
          echo "${{ secrets.KEYS_TAR_ASC }}" > .keys.tar.gz.asc
          gpg -d --passphrase "${{ secrets.KEYS_PASSPHRASE }}" --batch .keys.tar.gz.asc > .keys.tar.gz
          tar xzf .keys.tar.gz

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v14.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          WAITERROBOT_VERSION_STRING: ${{ github.ref_name }}
        with:
          command: make copied-site
          extra_flags: -f ci.conveyor.conf
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
