name: Conveyor Deploy
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: linux
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test
        run: ./gradlew test --stacktrace
        env:
          env: CI
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Build
        run: ./gradlew jar -PversionString="${{ github.ref_name }}" # TODO use "proguardReleaseJars" as this also uses Pro-Guard (but there needs to be more configuration [ProGuard, gradle and conveyor])
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Extract secrets
        run: |
          echo "${{ secrets.KEYS_TAR_ASC }}" > .keys.tar.gz.asc
          gpg -d --passphrase "${{ secrets.KEYS_PASSPHRASE }}" --batch .keys.tar.gz.asc > .keys.tar.gz
          tar xzf .keys.tar.gz
          cd ..

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v12.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
        with:
          command: make copied-site
          extra_flags: -f ci.conveyor.conf
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1

      - name: Create latest
        run: |
          cd build/compose/binaries/main/${{ matrix.pkg }}/
          cp ./* ./WaiterRobot-Desktop-latest.${{ matrix.pkg}}

      - name: Move to release server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build/compose/binaries/main/${{ matrix.pkg }}
          remote: /var/www/datepoll-share/WaiterRobot/Desktop-Releases/${{ matrix.pkg}}
          host: ${{ secrets.RELEASES_SSH_HOST }}
          port: ${{ secrets.RELEASES_SSH_PORT }}
          username: ${{ secrets.RELEASES_SSH_USER }}
          privateKey: ${{ secrets.RELEASES_SSH_PRIVATE_KEY }}
