name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # TODO run tests?

      - name: Create distributable
        run: ./gradlew packageDistributionForCurrentOS # TODO use "packageReleaseDistributionForCurrentOS" as this also uses Pro-Guard (but there needs to be more configuration)
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3g"

      - name: Release Linux
        if: matrix.os == 'ubuntu-latest'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Matrix strategy -> executed multiple times
          artifacts: "build/compose/binaries/main/deb/Mediator*"

      - name: Release Mac
        if: matrix.os == 'macos-latest'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Matrix strategy -> executed multiple times
          artifacts: "build/compose/binaries/main/dmg/Mediator*"

      - name: Release Windows
        if: matrix.os == 'windows-latest'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Matrix strategy -> executed multiple times
          artifacts: "build\compose\binaries\main\exe\Mediator*"